<%@ Page MasterPageFile="~/doc.master" Language="C#" Title="(will be set by sitemap)" %>

<asp:Content ID="Content2" ContentPlaceHolderID="MainContentPlaceHolder" runat="server">

  <h1>Nová licence - licence</h1>
  <p>
  Na této záložce lze vidět informace o nově vytvořené licenci, které budou zapsány do <a href="../../../../../../alvao-asset-management/software-management/licenses">registru licencí</a></p>
  <p>Možnosti:</p>
  <ul>
 <li><strong>Název licence</strong> - zadejte celý název licence, abyste ji později mohli v seznamu jednoznačně identifikovat. Ve výchozím nastavení je název stejný jako název produktu. Pokud pracujete s <a href="../new-license">balíčkem licencí</a>, musíte název licence zadat ručně.</li> <li><strong>Jazyk</strong> - vyberte jazyk licence, pokud je licence vázána na určitý jazyk. </li>
 <li><strong>Počet</strong> - zadejte počet vlastněných licencí.</li> <li><strong>Licenční model</strong> - vyberte metodu licencování nebo CAL: <ul> <li><strong>per device (na zařízení</strong> ) - přiřaďte licenční položky počítačům. </li>
 <li><strong>na uživatele</strong> - přidělení licenčních položek uživatelům. Licence se pak vztahuje na všechny počítače uživatele (tj, počítače, které má uživatel pod sebou ve <a href="../../../../../../alvao-asset-management/implementation/tree-design">stromu objektů</a>).</li> <li><strong>per connection</strong> - typicky u serverových licencí je počet aktivních připojení omezen.</li> <li><strong>per processor</strong> - typicky jsou serverové produkty licencovány podle počtu procesorů.</li> <li><strong>per core</strong> - typicky jsou serverové produkty licencovány</li> </ul> </li>na <li> <ul> <li> <em>jádro,</em></li> </ul> </li>tj. <li> <ul> <li>podle počtu výpočetních jader v procesoru.</li> </ul> </li> <li><strong>Režim licence</strong> - vyberte režim licence z nabídky nebo zadejte vlastní.</li>

 <li><strong>Platí od</strong> - zadejte datum začátku platnosti licence.</li> <li><strong>Platí do</strong> - zadejte datum vypršení platnosti licence, pokud je licence časově omezená.</li> <li><strong>Upgrade/podpora do</strong> - zadejte datum, kdy končí podpora produktu (a je vyžadován upgrade).</li> <li> <div class="tip"> <div class="icon"></div><div class="title">Tip:</div> </div> </li>Na <li> <div class="tip">blížící se konec platnosti licence nebo podpory můžete být upozorněni e-mailem. Další informace naleznete v části <a href="../../../../../../alvao-asset-management/implementation/maintenance-reports">Hlášení o údržbě</a></div></li>. <li><strong>Typ licence</strong> - vyberte typ licence.  <ul>
  <li><strong>Normal</strong> - normální (krabicová) licence.</li>
  <li><strong>Unlimited volume license</strong> - licence pro neomezený počet instalací, použití a uživatelů.</li>
  <li><strong>Plovoucí</strong> - použití licence je chráněno speciálním softwarem, hardwarovým klíčem nebo přístupovými právy. Licenci lze přiřadit více subjektům, než je počet nastavený v poli počet.  </li>
  <li><strong>OEM</strong> - licence OEM při zakoupení nového počítače nebo zařízení (komponenty).</li>
  <li><strong>CAL</strong> - Licence CAL (licence pro klientský přístup) nebo licence pro produkt, který nemá instalaci v počítači. Tato licence nebude vykázána jako "přebytečná".</li>
  </ul>
 <li><strong>Hardlock</strong> - povolte, pokud licence vyžaduje ochranu hardwarovým klíčem. Příznak "Hardlock" lze zaregistrovat pouze pro "plovoucí" licenci</li>. <li><strong>Licenční balíček</strong> - Tato možnost určuje, zda je licence součástí balíčku. Volba se nastavuje podle toho, zda byla v okně <a href="../new-license">Nová licence - produkt</a> vybrána možnost <strong>Balíček licencí</strong>.</li> <li><strong>Pokrýt součásti bez instalace balíčku</strong> - vypněte, pokud se tato licence nevztahuje na instalace součástí balíčku, pokud není balíček nainstalován. Tato volba nemá vliv na balíčky na kartě Náhradní produkty, kde jsou instalace součástí pokryty vždy bez ohledu na instalaci balíčku.</li> <li><strong>Přiřazovat automaticky</strong> - zapněte, pokud má systém automaticky přidělovat a odebírat tuto licenci všem počítačům v aktivní evidenci. Tuto volbu nelze zapnout, pokud je <em>Model licence</em> typu <em>na uživatele</em>nebo <em>Typ licence</em> typu <em>OEM licence</em>. <br />Pokud je tato volba aktivní: <ul>. <li>Systém přidělí tuto licenci vždy, když existuje nějaká instalace produktu, která může být pokryta touto licencí, a zároveň tato instalace není pokryta jinou licencí.</li> <li>Pokud je produkt odinstalován (detekován nebo ručně), systém licenci opět automaticky uvolní: <ul> <li>Pokud jsou v položce zadány nějaké údaje (sériové číslo, inventární číslo, nákladové středisko atd. ), položka pouze zruší počítač.</li> <li>Systém automaticky uvolní pouze položky, které byly automaticky přiděleny.</li> </ul> </li> <li> <ul> <li>Ručně přidělené položky se automaticky neodvolávají.</li> </ul> </li> <li>Je možné ručně přidělit nebo přesunout licence (i ty, které byly dříve přiděleny automaticky). <br />Pokud je položka přidělena ručně, systém ji automaticky neodvolá, ale zůstane trvale přidělena.</li> <li>Licence se automaticky přidělují podle organizace a nákladového střediska:<ul> <li>Shoduje se organizace licence a počítače a nákladové středisko licence a počítače (obojí může být prázdné).</li> <li>Shoduje se organizace licence a počítače a nákladové středisko licence je prázdné (licence je zakoupena pro celou organizaci, takže nákladové středisko počítače může být libovolné)</li> </ul></li>.
 <li><ul> <li>Licence není přiřazena k žádné organizaci a nákladové středisko licence a počítače se shodují (obě mohou být prázdná).</li> <li>Licence není přiřazena k žádné organizaci a nákladové středisko licence je prázdné (licence je zakoupena pro celou organizaci, takže nákladové středisko počítače může být libovolné).</li></ul> <br />Systém tedy automaticky nepřiřadí licenci k počítači s jinou organizací a nákladovým střediskem (je však možné ručně přiřadit licenci z jiného nákladového střediska nebo jiné organizace).</li> <li>Dochází k automatickému přiřazení/odřazení: <ul>
 <li>Po určité době po uložení licence se zapnutou volbou &quot;Automaticky přiřadit&quot;.</li> <li> Ihned po jakémkoli vyhodnocení SW detekce počítače (AM Collector, ruční načtení výsledku detekce do AM Console).</li> <li>Jednou denně (v noci) pomocí AM Collector. Vyhledají se všechny počítače v evidenci, kterým lze automaticky přiřadit/odebrat některé licence.</li> </ul> <li><a href="../auto-assign-license-settings"> Nastavení ...]</a></li> </ul> </li> <li><strong>Povolit přiřazení více licencí jednomu objektu</strong> - povolte, pokud je možné licenci přiřadit stejnému objektu vícekrát.</li> <li><strong>Aktivační klíč</strong> - pokud má licence pouze jeden aktivační klíč (multilicence), zadejte jej do tohoto pole. V opačném případě zadejte aktivační klíče do pole v položkách licence. <div class="caution">
 <div class="icon">
  </div>
  
 <div class="title">Pozor</div>: Tato hodnota bude v databázi uložena v nezašifrované podobě! </div>
 <div class="note">
 <div class="icon">
  </div>
  
 <div class="title">Poznámka</div>: Pokud zadáte aktivační klíč pro licenci, bude do všech nově vytvořených licenčních záznamů automaticky přidán aktivační klíč podle předpisu pro danou licenci. </div> </li>

  
  
 <li><strong>Inventární číslo</strong> - zadání inventárního čísla, pod kterým bude tato licence evidována v účetním systému.</li> <li><a href="../../../../tools/lists/documents">Certifikát</a> - výběr certifikátu z evidence dokladů.</li> <li><strong>Požadavek</strong> - zadání čísla požadavku vztahujícího se k licenci (např. požadavek na nákup, ke kterému se zakoupená licence vztahuje</li>). <li><strong>Organizace</strong> - výběr organizace, pro kterou je zakoupená licence určena. Pokud nezvolíte žádnou hodnotu, bude licence dostupná pro všechny organizace. Toto pole se zobrazuje pouze u uživatelů, kteří mají nastaveno <a href="../../../../../alvao-webapp/administration/asset-management/software-licenses-security">Zabezpečení softwarových licencí</a>. oprávnění měnit licence alespoň od jedné organizace.</li> <li><strong>Nákladové středisko</strong> - zadejte <a href="../../../license-and-install-overview/view">nákladové středisko</a>, pro které je zakoupená licence určena. Pokud nezadáte žádnou hodnotu, bude licence dostupná pro všechna nákladová střediska.</li> <li><strong>Cena</strong> - zadejte cenu, za kterou byla licence zakoupena. Zadejte hodnotu v celočíselném tvaru.</li> <li><strong>Webová adresa pro stažení</strong> - zadejte adresu, odkud byl software stažen, pokud se jedná</li>o <li> <em>internetovou licenci</em>.</li> <li><strong>Poznámka</strong> - zadejte poznámku k zakoupené licenci</li></ul>
</asp:Content>
