<%@ Page MasterPageFile="~/doc.master" Language="C#" Title="(will be set by sitemap)" %>

<asp:Content ID="Content2" ContentPlaceHolderID="MainContentPlaceHolder" runat="server">

    <h1>Adding an object to the tree</h1>
    <ol>
        <li>In the tree, right-click on the object you want to add a new object to. If you want to insert the object into the root of the tree, click in the area where there are no tree entries.</li>
        <li>From the local menu, select <strong>New Object</strong>.</li>
        <li>The <strong>New Object - Select a template object</strong> window will open on the screen in the tab <a href="../../list-of-windows/alvao-asset-management-console/edit/new-object/object-template">Object Templates</a>, which contains a menu of object templates. In the window, select the type of object you want to insert into the tree and press the <strong>OK</strong> button.</li>
        <li>If a history is being kept for the new object (its template is set to do so), or if it is inserted into an object that has a history, the window will open on the screen <a href="../../list-of-windows/alvao-asset-management-console/date-time"> Date and Time</a> to specify the date and time the object was created. You can change the date and time if you are adding the object to the database after the fact.</li>
        <li>The new object appears in the tree. When you select the <strong>Edit</strong> command from the local object menu, a window opens on the screen <a href="../../list-of-windows/alvao-asset-management-console/edit/object/general">Object</a>, where you can change its icon, name (unless the name is generated by one of the properties), and possibly its type. You can edit the list of properties of an object on the <strong>Properties</strong> tab in <a href="../../list-of-windows/alvao-asset-management-console">main window</a>.</li>
    </ol>
    <div class="tip">
        <div class="icon"></div>
        <div class="title">Tip:</div>
        When in the <a href="../../list-of-windows/alvao-asset-management-console/date-time">Date and Time</a> to enter the date and time, if you enable the <em>Don't show this window next time and use the current date and time</em> option, the window will not open next time. You can enable it again by <em>Help - Settings</em>, where on the <em>General</em> tab you turn off the <em>Create history records with current date and time</em> option.
    </div>
    <div class="note">
        <div class="icon"></div>
        <div class="title">Note:</div>
        You can customize and extend the object templates menu with your own objects, see <a href="../implementation/object-templates">Object templates</a>.
    </div>
</asp:Content>
