<%@ Page masterpagefile="~/doc.master" language="C#" title="(will be set by sitemap)" %>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContentPlaceHolder" runat="server">

<h1>Designation</h1>
<p>This tab allows you to enter the identification number <a href="../../../../../alvao-asset-management/documents">
document</a> or <a href="../../../../../alvao-asset-management/software-management/licenses#media">
media</a>.</p>
<p>Options:</p>
	<ul>
 <li><strong>Identification Number</strong> - enter the document or media number.<br/> If the number is generated by <a href="../../../../../alvao-asset-management/documents/sequences">
 by a number series</a>, it cannot be changed. If you want to enter the number manually and not use a sequence, change the appropriate numeric sequence setting in the <a href="../numeric-sequences">
 Numeric sequences</a>.</li>
	</ul>
</asp:Content>
