<%@ Page masterpagefile="~/doc.master" language="C#" title="(will be set by sitemap)" %>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContentPlaceHolder" runat="server">

<h1>New document</h1>
 <p>On this page, you can create a new document.</p>

  <p>
  Options:</p>

 <ul>
    <li><b>Document type</b> - choose the <a href="../../../alvao-asset-management/documents">type</a> of the document. </li>
    <li><b>Document name</b> - in case you use the <em>Document number</em> field as a unique document identifier, you may skip this field or enter descriptive information to easily identify the document in listings. If you don&#39;t use the <em>Document number</em> field, this field is mandatory, and entering a unique document name is recommended.</li>
    <li><b>Document number</b> - if the number is not generated by a <a href="../../alvao-asset-management-console/tools/lists/numeric-sequences">sequence</a> nor the <em>Document name</em> is not used to uniquely identify documents, enter a unique document identifier in this field. </li>
    <li><b>Attachments</b> - (optional) add a file or link attachments to the document. </li>
    <li><b>Objects</b> - (optional) link the document to specific objects. </li>
    <li><b>Licenses</b> - (optional) link the document to specific software licenses. </li>
    <li><b>External document number</b> - (optional) enter the original number of the document issued by your vendor, partner, etc. </li>
    <li><b>Issue date</b> - (optional) enter the issue date of the document. </li>
    <li><b>Vendor</b> (optional) - type in at least part of the vendor name and then select the vendor from the drop-down list. This field is available only for the document type <em>Invoice</em>.</li>
    <li><b>Document folder</b> - select the <a href="../administration/asset-management/document-folders">document folder</a> from the list. </li>
    <li><b>Notes</b> - (optional) enter additional information about the document. </li>
</ul>



</asp:Content>
